CREATE TABLE [EDW].[fact_SalesAnalysis] (
    [salesSK]            BIGINT        IDENTITY (1, 1) NOT NULL,
    [TransactionNo]      NVARCHAR (50) NULL,
    [TransDateSK]        INT           NULL,
    [TransHourSK]        INT           NULL,
    [OrderDateSK]        INT           NULL,
    [OrderHourSK]        INT           NULL,
    [DeliveryDateSK]     INT           NULL,
    [ChannelSK]          INT           NULL,
    [CustomerSK]         INT           NULL,
    [EmployeeSK]         INT           NULL,
    [ProductSK]          INT           NULL,
    [StoreSK]            INT           NULL,
    [PromotionSK]        INT           NULL,
    [Quantity]           FLOAT (53)    NULL,
    [TaxAmount]          FLOAT (53)    NULL,
    [LineAmount]         FLOAT (53)    NULL,
    [LineDiscountAmount] FLOAT (53)    NULL,
    [LoadDate]           DATETIME      DEFAULT (getdate()) NULL,
    CONSTRAINT [edw_factSalesAnalysis_sk] PRIMARY KEY CLUSTERED ([salesSK] ASC),
    CONSTRAINT [edw_sales_customer_fk] FOREIGN KEY ([CustomerSK]) REFERENCES [EDW].[DimCustomer] ([customerSK]),
    CONSTRAINT [edw_sales_deliverydate_fk] FOREIGN KEY ([DeliveryDateSK]) REFERENCES [EDW].[DimDate] ([dateSK]),
    CONSTRAINT [edw_sales_employee_fk] FOREIGN KEY ([EmployeeSK]) REFERENCES [EDW].[DimEmployee] ([employeeSK]),
    CONSTRAINT [edw_sales_orderdate_fk] FOREIGN KEY ([OrderDateSK]) REFERENCES [EDW].[DimDate] ([dateSK]),
    CONSTRAINT [edw_sales_orderhour_fk] FOREIGN KEY ([OrderHourSK]) REFERENCES [EDW].[DimTime] ([TimeSk]),
    CONSTRAINT [edw_sales_poschannel_fk] FOREIGN KEY ([ChannelSK]) REFERENCES [EDW].[DimPOSChannel] ([poschannelSK]),
    CONSTRAINT [edw_sales_product_fk] FOREIGN KEY ([ProductSK]) REFERENCES [EDW].[DimProduct] ([productSK]),
    CONSTRAINT [edw_sales_promotion_fk] FOREIGN KEY ([PromotionSK]) REFERENCES [EDW].[DimPromotion] ([promotionSK]),
    CONSTRAINT [edw_sales_store_fk] FOREIGN KEY ([StoreSK]) REFERENCES [EDW].[DimStore] ([storeSK]),
    CONSTRAINT [edw_sales_transdate_fk] FOREIGN KEY ([TransDateSK]) REFERENCES [EDW].[DimDate] ([dateSK]),
    CONSTRAINT [edw_sales_transhour_fk] FOREIGN KEY ([TransHourSK]) REFERENCES [EDW].[DimTime] ([TimeSk])
);

