{
  "name": "SemanticModel",
  "id": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-CA",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/isaac_awotwe\\ISAACMDX;TescaDB",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "isaac_awotwe\\ISAACMDX",
            "database": "TescaDB"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "isaac_awotwe\\isaacmdx;TescaDB",
          "Username": "sa",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "EDW fact_SalesAnalysis",
        "isHidden": true,
        "columns": [
          {
            "name": "salesSK",
            "dataType": "int64",
            "sourceColumn": "salesSK"
          },
          {
            "name": "TransactionNo",
            "dataType": "string",
            "sourceColumn": "TransactionNo"
          },
          {
            "name": "TransDateSK",
            "dataType": "int64",
            "sourceColumn": "TransDateSK"
          },
          {
            "name": "TransHourSK",
            "dataType": "int64",
            "sourceColumn": "TransHourSK"
          },
          {
            "name": "OrderDateSK",
            "dataType": "int64",
            "sourceColumn": "OrderDateSK"
          },
          {
            "name": "OrderHourSK",
            "dataType": "int64",
            "sourceColumn": "OrderHourSK"
          },
          {
            "name": "DeliveryDateSK",
            "dataType": "int64",
            "sourceColumn": "DeliveryDateSK"
          },
          {
            "name": "ChannelSK",
            "dataType": "int64",
            "sourceColumn": "ChannelSK"
          },
          {
            "name": "CustomerSK",
            "dataType": "int64",
            "sourceColumn": "CustomerSK"
          },
          {
            "name": "EmployeeSK",
            "dataType": "int64",
            "sourceColumn": "EmployeeSK"
          },
          {
            "name": "ProductSK",
            "dataType": "int64",
            "sourceColumn": "ProductSK"
          },
          {
            "name": "StoreSK",
            "dataType": "int64",
            "sourceColumn": "StoreSK"
          },
          {
            "name": "PromotionSK",
            "dataType": "int64",
            "sourceColumn": "PromotionSK"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "Quantity"
          },
          {
            "name": "TaxAmount",
            "dataType": "double",
            "sourceColumn": "TaxAmount"
          },
          {
            "name": "LineAmount",
            "dataType": "double",
            "sourceColumn": "LineAmount"
          },
          {
            "name": "LineDiscountAmount",
            "dataType": "double",
            "sourceColumn": "LineDiscountAmount"
          },
          {
            "name": "LoadDate",
            "dataType": "dateTime",
            "sourceColumn": "LoadDate"
          }
        ],
        "partitions": [
          {
            "name": "EDW fact_SalesAnalysis20231231",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/isaac_awotwe\\ISAACMDX;TescaDB\",",
                "    EDW_fact_SalesAnalysis = Source{[Schema=\"EDW\",Item=\"fact_SalesAnalysis\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(EDW_fact_SalesAnalysis, each [TransDateSK] > 20221231 and [TransDateSK] <= 20231231)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/isaac_awotwe\\ISAACMDX;TescaDB\",",
                  "    EDW_fact_SalesAnalysis = Source{[Schema=\"EDW\",Item=\"fact_SalesAnalysis\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(EDW_fact_SalesAnalysis, each [TransDateSK] > 20221231 and [TransDateSK] <= 20231231)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "EDW fact_SalesAnalysis20221231",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/isaac_awotwe\\ISAACMDX;TescaDB\",",
                "    EDW_fact_SalesAnalysis = Source{[Schema=\"EDW\",Item=\"fact_SalesAnalysis\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(EDW_fact_SalesAnalysis, each [TransDateSK] <= 20221231)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/isaac_awotwe\\ISAACMDX;TescaDB\",",
                  "    EDW_fact_SalesAnalysis = Source{[Schema=\"EDW\",Item=\"fact_SalesAnalysis\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(EDW_fact_SalesAnalysis, each [TransDateSK] <= 20221231)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "EDW fact_SalesAnalysis",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/isaac_awotwe\\ISAACMDX;TescaDB\",",
                "    EDW_fact_SalesAnalysis = Source{[Schema=\"EDW\",Item=\"fact_SalesAnalysis\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(EDW_fact_SalesAnalysis, each [TransDateSK] > 20231231)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/isaac_awotwe\\ISAACMDX;TescaDB\",",
                  "    EDW_fact_SalesAnalysis = Source{[Schema=\"EDW\",Item=\"fact_SalesAnalysis\"]}[Data]",
                  "in",
                  "    EDW_fact_SalesAnalysis</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "NetAmount",
            "expression": "SUMX('EDW fact_SalesAnalysis','EDW fact_SalesAnalysis'[TaxAmount]+'EDW fact_SalesAnalysis'[LineAmount]-'EDW fact_SalesAnalysis'[LineDiscountAmount])"
          },
          {
            "name": "Total Tax Amount",
            "expression": "SUM('EDW fact_SalesAnalysis'[TaxAmount])"
          },
          {
            "name": "Total Line Amount",
            "expression": "SUM('EDW fact_SalesAnalysis'[LineAmount])"
          },
          {
            "name": "Total Line Discount Amount",
            "expression": "SUM('EDW fact_SalesAnalysis'[LineDiscountAmount])"
          },
          {
            "name": "Total Transactions",
            "expression": "COUNTROWS('EDW fact_SalesAnalysis')"
          },
          {
            "name": "Total Quantity",
            "expression": " SUM('EDW fact_SalesAnalysis'[Quantity])",
            "kpi": {
              "targetExpression": "100",
              "statusGraphic": "Traffic Light - Single",
              "statusExpression": [
                "var x='EDW fact_SalesAnalysis'[Total Quantity] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<40,-1,",
                "\t                If(x<80,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "40"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "80"
                }
              ]
            }
          }
        ]
      },
      {
        "name": "Customer",
        "columns": [
          {
            "name": "customerSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "customerSK"
          },
          {
            "name": "CustomerID",
            "dataType": "int64",
            "sourceColumn": "CustomerID"
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name"
          },
          {
            "name": "Address",
            "dataType": "string",
            "sourceColumn": "Address"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State"
          },
          {
            "name": "CreatedDate",
            "dataType": "dateTime",
            "sourceColumn": "CreatedDate"
          },
          {
            "name": "EffectiveDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EffectiveDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/isaac_awotwe\\ISAACMDX;TescaDB\",",
                "    EDW_DimCustomer = Source{[Schema=\"EDW\",Item=\"DimCustomer\"]}[Data]",
                "in",
                "    EDW_DimCustomer"
              ]
            }
          }
        ]
      },
      {
        "name": "Delivery Date",
        "columns": [
          {
            "name": "dateSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "dateSK"
          },
          {
            "name": "Delivery BusinessDate",
            "dataType": "dateTime",
            "sourceColumn": "BusinessDate"
          },
          {
            "name": "Delivery BusinessYear",
            "dataType": "int64",
            "sourceColumn": "BusinessYear"
          },
          {
            "name": "Delivery BusinessMonth",
            "dataType": "int64",
            "sourceColumn": "BusinessMonth"
          },
          {
            "name": "Delivery BusinessQuarter",
            "dataType": "string",
            "sourceColumn": "BusinessQuarter"
          },
          {
            "name": "Delivery EnglishMonth",
            "dataType": "string",
            "sourceColumn": "EnglishMonth"
          },
          {
            "name": "Delivery SpanishMonth",
            "dataType": "string",
            "sourceColumn": "SpanishMonth"
          },
          {
            "name": "Delivery FrenchMonth",
            "dataType": "string",
            "sourceColumn": "FrenchMonth"
          },
          {
            "name": "Delivery EnglishDayofWeek",
            "dataType": "string",
            "sourceColumn": "EnglishDayofWeek"
          },
          {
            "name": "Delivery SpanishDayofWeek",
            "dataType": "string",
            "sourceColumn": "SpanishDayofWeek"
          },
          {
            "name": "Delivery FrenchDayofWeek",
            "dataType": "string",
            "sourceColumn": "FrenchDayofWeek"
          },
          {
            "name": "LoadDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LoadDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/isaac_awotwe\\ISAACMDX;TescaDB\",",
                "    EDW_DimDate = Source{[Schema=\"EDW\",Item=\"DimDate\"]}[Data]",
                "in",
                "    EDW_DimDate"
              ]
            }
          }
        ]
      },
      {
        "name": "Sales Person",
        "columns": [
          {
            "name": "employeeSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "employeeSK"
          },
          {
            "name": "Salerperson ID",
            "dataType": "int64",
            "sourceColumn": "EmployeeID"
          },
          {
            "name": "SalerpersonNo",
            "dataType": "string",
            "sourceColumn": "EmployeeNumber"
          },
          {
            "name": "Sales Person",
            "dataType": "string",
            "sourceColumn": "EmployeeName"
          },
          {
            "name": "DateofBirth",
            "dataType": "dateTime",
            "sourceColumn": "DateofBirth"
          },
          {
            "name": "MaritalStatus",
            "dataType": "string",
            "sourceColumn": "MaritalStatus"
          },
          {
            "name": "EffectiveStartDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EffectiveStartDate"
          },
          {
            "name": "EffectiveEndDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EffectiveEndDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/isaac_awotwe\\ISAACMDX;TescaDB\",",
                "    EDW_DimEmployee = Source{[Schema=\"EDW\",Item=\"DimEmployee\"]}[Data]",
                "in",
                "    EDW_DimEmployee"
              ]
            }
          }
        ]
      },
      {
        "name": "POSChannel",
        "columns": [
          {
            "name": "poschannelSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "poschannelSK"
          },
          {
            "name": "ChannelID",
            "dataType": "int64",
            "sourceColumn": "ChannelID"
          },
          {
            "name": "ChannelNumber",
            "dataType": "string",
            "sourceColumn": "ChannelNumber"
          },
          {
            "name": "DeviceModel",
            "dataType": "string",
            "sourceColumn": "DeviceModel"
          },
          {
            "name": "SerialNumber",
            "dataType": "string",
            "sourceColumn": "SerialNumber"
          },
          {
            "name": "InstallationDate",
            "dataType": "dateTime",
            "sourceColumn": "InstallationDate"
          },
          {
            "name": "EffectiveStartDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EffectiveStartDate"
          },
          {
            "name": "EffectiveEndDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EffectiveEndDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/isaac_awotwe\\ISAACMDX;TescaDB\",",
                "    EDW_DimPOSChannel = Source{[Schema=\"EDW\",Item=\"DimPOSChannel\"]}[Data]",
                "in",
                "    EDW_DimPOSChannel"
              ]
            }
          }
        ]
      },
      {
        "name": "Product",
        "columns": [
          {
            "name": "productSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "productSK"
          },
          {
            "name": "ProductID",
            "dataType": "int64",
            "sourceColumn": "ProductID"
          },
          {
            "name": "Product",
            "dataType": "string",
            "sourceColumn": "Product"
          },
          {
            "name": "ProductNumber",
            "dataType": "string",
            "sourceColumn": "ProductNumber"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          },
          {
            "name": "UnitPrice",
            "dataType": "double",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "EffectiveStartDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EffectiveStartDate"
          },
          {
            "name": "EffectiveEndDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EffectiveEndDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/isaac_awotwe\\ISAACMDX;TescaDB\",",
                "    EDW_DimProduct = Source{[Schema=\"EDW\",Item=\"DimProduct\"]}[Data]",
                "in",
                "    EDW_DimProduct"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "ProductHierarchy",
            "levels": [
              {
                "name": "Department",
                "ordinal": 0,
                "column": "Department"
              },
              {
                "name": "Product",
                "ordinal": 1,
                "column": "Product"
              }
            ]
          }
        ]
      },
      {
        "name": "Promotion",
        "columns": [
          {
            "name": "promotionSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "promotionSK"
          },
          {
            "name": "PromotionID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PromotionID"
          },
          {
            "name": "Promotion",
            "dataType": "string",
            "sourceColumn": "Promotion"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "sourceColumn": "EndDate"
          },
          {
            "name": "DiscountPercent",
            "dataType": "double",
            "sourceColumn": "DiscountPercent"
          },
          {
            "name": "EffectiveDate",
            "dataType": "dateTime",
            "sourceColumn": "EffectiveDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/isaac_awotwe\\ISAACMDX;TescaDB\",",
                "    EDW_DimPromotion = Source{[Schema=\"EDW\",Item=\"DimPromotion\"]}[Data]",
                "in",
                "    EDW_DimPromotion"
              ]
            }
          }
        ]
      },
      {
        "name": "Store",
        "columns": [
          {
            "name": "storeSK",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "storeSK"
          },
          {
            "name": "StoreID",
            "dataType": "int64",
            "sourceColumn": "StoreID"
          },
          {
            "name": "Store",
            "dataType": "string",
            "sourceColumn": "Store"
          },
          {
            "name": "Address",
            "dataType": "string",
            "sourceColumn": "Address"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State"
          },
          {
            "name": "EffectiveDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EffectiveDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/isaac_awotwe\\ISAACMDX;TescaDB\",",
                "    EDW_DimStore = Source{[Schema=\"EDW\",Item=\"DimStore\"]}[Data]",
                "in",
                "    EDW_DimStore"
              ]
            }
          }
        ]
      },
      {
        "name": "TransHour",
        "columns": [
          {
            "name": "TimeSk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TimeSk"
          },
          {
            "name": "Trans Time Hour",
            "dataType": "int64",
            "sourceColumn": "TimeHour"
          },
          {
            "name": "Trans Time Interval",
            "dataType": "string",
            "sourceColumn": "TimeInterval"
          },
          {
            "name": "Trans Business Hour",
            "dataType": "string",
            "sourceColumn": "BusinessHour"
          },
          {
            "name": "Trans Period of Day",
            "dataType": "string",
            "sourceColumn": "PeriodofDay"
          },
          {
            "name": "LoadDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LoadDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/isaac_awotwe\\ISAACMDX;TescaDB\",",
                "    EDW_DimTime = Source{[Schema=\"EDW\",Item=\"DimTime\"]}[Data]",
                "in",
                "    EDW_DimTime"
              ]
            }
          }
        ]
      },
      {
        "name": "OrderHour",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "TimeSk",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "TransHour[TimeSk]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order Time Hour",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "TransHour[Trans Time Hour]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order Time Interval",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "TransHour[Trans Time Interval]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order Business Hour",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "TransHour[Trans Business Hour]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order Period of Day",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "TransHour[Trans Period of Day]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "LoadDate",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "TransHour[LoadDate]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "'TransHour'"
            }
          }
        ]
      },
      {
        "name": "TransDate",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "dateSK",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Delivery Date[dateSK]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Trans BusinessDate",
            "dataType": "dateTime",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery BusinessDate]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Trans BusinessYear",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery BusinessYear]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Trans BusinessMonth",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery BusinessMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Trans BusinessQuarter",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery BusinessQuarter]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Trans EnglishMonth",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery EnglishMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Trans SpanishMonth",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery SpanishMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Trans FrenchMonth",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery FrenchMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Trans EnglishDayofWeek",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery EnglishDayofWeek]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Trans SpanishDayofWeek",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery SpanishDayofWeek]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Trans FrenchDayofWeek",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery FrenchDayofWeek]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "LoadDate",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Delivery Date[LoadDate]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "'Delivery Date'"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "TransDateHierarchy",
            "levels": [
              {
                "name": "Trans BusinessQuarter",
                "ordinal": 1,
                "column": "Trans BusinessQuarter"
              },
              {
                "name": "Trans BusinessYear",
                "ordinal": 0,
                "column": "Trans BusinessYear"
              },
              {
                "name": "Trans EnglishMonth",
                "ordinal": 2,
                "column": "Trans EnglishMonth"
              }
            ]
          }
        ]
      },
      {
        "name": "OrderDate",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "dateSK",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Delivery Date[dateSK]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order Business Date",
            "dataType": "dateTime",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery BusinessDate]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order Business Year",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery BusinessYear]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order Business Month",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery BusinessMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order Business Quarter",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery BusinessQuarter]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order English Month",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery EnglishMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order Spanish Month",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery SpanishMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order French Month",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery FrenchMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order English Day of Week",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery EnglishDayofWeek]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order SpanishDayofWeek",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery SpanishDayofWeek]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order FrenchDayofWeek",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "Delivery Date[Delivery FrenchDayofWeek]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "LoadDate",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Delivery Date[LoadDate]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "'Delivery Date'"
            }
          }
        ]
      },
      {
        "name": "TransactionNo",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "TransactionNo",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "EDW fact_SalesAnalysis[TransactionNo]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "VALUES('EDW fact_SalesAnalysis'[TransactionNo])"
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "e3c4b2ca-4ceb-4dce-822b-8ac1cfe3eae1",
        "fromTable": "EDW fact_SalesAnalysis",
        "fromColumn": "CustomerSK",
        "toTable": "Customer",
        "toColumn": "customerSK"
      },
      {
        "name": "a5975918-43c7-41f4-ada4-eb2cb081f262",
        "fromTable": "EDW fact_SalesAnalysis",
        "fromColumn": "EmployeeSK",
        "toTable": "Sales Person",
        "toColumn": "employeeSK"
      },
      {
        "name": "b4a163c8-ac61-42a1-a45c-c282c015bc79",
        "fromTable": "EDW fact_SalesAnalysis",
        "fromColumn": "ChannelSK",
        "toTable": "POSChannel",
        "toColumn": "poschannelSK"
      },
      {
        "name": "fda8ab7b-f799-4524-bccb-4736e3365964",
        "fromTable": "EDW fact_SalesAnalysis",
        "fromColumn": "ProductSK",
        "toTable": "Product",
        "toColumn": "productSK"
      },
      {
        "name": "9dc9b3fb-acec-4e60-8dc9-90936c5ce5d7",
        "fromTable": "EDW fact_SalesAnalysis",
        "fromColumn": "PromotionSK",
        "toTable": "Promotion",
        "toColumn": "promotionSK"
      },
      {
        "name": "ccc20469-ad79-4146-97d0-56fd4540d4e9",
        "fromTable": "EDW fact_SalesAnalysis",
        "fromColumn": "StoreSK",
        "toTable": "Store",
        "toColumn": "storeSK"
      },
      {
        "name": "655b58ed-6fe9-4fdf-a173-7cc2ca8ace82",
        "fromTable": "EDW fact_SalesAnalysis",
        "fromColumn": "TransHourSK",
        "toTable": "TransHour",
        "toColumn": "TimeSk"
      },
      {
        "name": "d42fc633-07b5-47d6-9530-ada777f50047",
        "fromTable": "EDW fact_SalesAnalysis",
        "fromColumn": "OrderHourSK",
        "toTable": "OrderHour",
        "toColumn": "TimeSk"
      },
      {
        "name": "57885d6a-c90e-404f-a0dd-6711eb9c58cf",
        "fromTable": "EDW fact_SalesAnalysis",
        "fromColumn": "DeliveryDateSK",
        "toTable": "Delivery Date",
        "toColumn": "dateSK"
      },
      {
        "name": "0dac2c6a-6363-403d-8725-a67558dd10f8",
        "fromTable": "EDW fact_SalesAnalysis",
        "fromColumn": "TransDateSK",
        "toTable": "TransDate",
        "toColumn": "dateSK"
      },
      {
        "name": "9721684b-829d-406a-9c17-4bc302ca7d01",
        "fromTable": "EDW fact_SalesAnalysis",
        "fromColumn": "OrderDateSK",
        "toTable": "OrderDate",
        "toColumn": "dateSK"
      },
      {
        "name": "9f1d0903-df03-43bc-bf6c-3338e14d0e02",
        "fromTable": "EDW fact_SalesAnalysis",
        "fromColumn": "TransactionNo",
        "toTable": "TransactionNo",
        "toColumn": "TransactionNo"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  }
}